### ISSUE TITLE
Error while running Veeam Script

### ISSUE THREAD

**Issue by AndriesSIT** [lordmilko/PrtgSensors#1]
When I run the Get-VeeamBackupStatus script I get the following error. The parameters seem to be correct. 

_<**Prtg>
    <Error>1</Error>
    <Text>An exception occurred while trying to process backups: Execution environment cannot be initialized to Remote</Text>
</Prtg>**_

Anyone have an idea?

**Comment by lordmilko** [comment]
Hi @andriesgithub,

* Please make sure the PRTG sensor is set to "Use Windows credentials of parent device"
* Please confirm that the Windows user the PRTG device is running as actually has permissions to connect to Veeam, which you can do by trying to log into the Veeam console as that user from the PRTG Probe server and/or running the `Connect-VBRServer <server>` command directly
* Please try running the script directly from a PowerShell prompt running as a user you know has access to connect to Veeam (such as yourself)

```
& C:\path\to\Get-VeeamBackupStatus.ps1 <server> <backupName>
```
Where **&lt;server&gt;** and &lt;backupName&gt; are the parameters you configured on the sensor's parameters in PRTG

* and then try again running the script as the Windows user the PRTG device is configured to authenticate as

**Comment by AndriesSIT** [comment]
Hi @lordmilko,

Thanks for your reply, sensor works great

How can I add multiple backup jobs? I have put all backup jobs in the parameter but it only shows the first one.

**Comment by lordmilko** [comment]
To monitor multiple backup jobs create a separate sensor for each job
