### ISSUE TITLE
Paremetres, not reading Job Name

### ISSUE THREAD

**Issue by anniehall2022** [lordmilko/PrtgSensors#5]
Hi there!

I am new using PRTG and this is the first custom sensor I've added.
No matter if I type double quotation marks or single ones when I set up the sensor, I always get the error:

**"Please specify the name of a backup job. If the job name contains spaces, surround the name in double quotation marks."**

It gets well the name of the server and credentials though.

How could I check what's wrong or any other idea?

Thanks in advance,

A.

**Comment by lordmilko** [comment]
There are two arguments you need to specify: the name of the backup server, and the name of the backup job

Can you please provide a screenshot of what you're typing in the parameters?

**Comment by anniehall2022** [comment]
exactly. I attach the screenshot. 
![sensor](https://user-images.githubusercontent.com/114484771/192779309-00f42d30-fb89-463f-bffc-88ca0aba21a3.JPG)

**Comment by anniehall2022** [comment]
Thanks for you quick answer!

**Comment by lordmilko** [comment]
You should not specify a comma when passing values to PowerShell functions. A comma is used in PowerShell to signify an array

Also, I don't know how PowerShell is going to treat `192.168.168.168` when passed as a literal like that. Normally a dot is used to signify a member access expression. In some scenarios PowerShell can automatically interpret illegal expressions as strings, I don't know if this is one of them

Can you please change your invocation to

```powershell
"192.168.168.168" "Name of the Job on Veeam"
```
and try again?

**Comment by anniehall2022** [comment]
I will use the hostname instead. Let me try.

**Comment by anniehall2022** [comment]
I get a different error:

**"An exception occurred while trying to process backups: Execution environment cannot be initialized to Remote"**

FYI, the PRTG server is within the domain and for security reasons, the veeam server is out, but they see eachother and the credentials are ok.

**Comment by lordmilko** [comment]
This is a Veeam error

Based on your screenshot it seems like your settings are incorrect: I believe you need to set it to run in the context of the Windows device, not the PRTG Probe

**Comment by anniehall2022** [comment]
what do you mean, exactly?

**Comment by lordmilko** [comment]
You have the following selected

* Usar contexto de seguridad del servico de sonda de PRTG

This is wrong. It should be set to use the Windows credentials, not the PRTG credentials

**Comment by anniehall2022** [comment]
You are right about that. I will change it now.
I appreciate it.

**Comment by anniehall2022** [comment]
I keep getting Credentials error eventhough I have checked it's correct. Error PE095. I am sure there is something else I am missing.... ;)

**Comment by lordmilko** [comment]
I have not tested running this script against non-domain servers

You may need to change the script to run under the context of the probe again, and then hack the script to specify the Veeam username and password to use

* https://helpcenter.veeam.com/docs/backup/powershell/connect-vbrserver.html?ver=110

**Comment by anniehall2022** [comment]
good point! Thank you!  I will try it and I will go back to you.

**Comment by anniehall2022** [comment]
Hi!

I could set up the conection between the PRTG and the Veeam backup server sucessfully but I am not sure if that could be a security issue so, I am going to leave it that way. I might try to change the script and add the credential as you mentioned earlier.

Thank you againg for your support.
